[package]
name = "tune"
version = "0.4.0"
authors = ["Woyten <woyten.tielesch@online.de>"]
description = "Create synthesizer tuning files for microtonal scales."
repository = "https://github.com/Woyten/tune/"
readme = "README.md"
keywords = ["microtonal", "music", "scales", "synthesizer", "tuning"]
license = "MIT"
edition = "2018"

[[bin]]
name = "tune"
path = "src-bin/main.rs"

[dependencies]
structopt = "0.2.14"

[dev-dependencies]
assert_approx_eq = "1.1.0"