[package]
name = "tune"
version = "0.6.0"
authors = ["Woyten <woyten.tielesch@online.de>"]
description = "Explore musical tunings and create synthesizer tuning files for microtonal scales."
repository = "https://github.com/Woyten/tune/"
readme = "README.md"
keywords = ["microtonal", "midi", "scales", "synthesizer", "tuning"]
license = "MIT"
edition = "2018"

[[bin]]
name = "tune"
path = "src-bin/main.rs"

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
structopt = "0.3.13"

[dev-dependencies]
assert_approx_eq = "1.1.0"