[package]
name = "tune"
version = "0.8.0"
authors = ["Woyten <woyten.tielesch@online.de>"]
description = "Explore musical tunings and create synthesizer tuning files for microtonal scales."
repository = "https://github.com/Woyten/tune/"
readme = "README.md"
keywords = ["microtonal", "midi", "scales", "synthesizer", "tuning"]
license = "MIT"
edition = "2018"

[dependencies]

[dev-dependencies]
assert_approx_eq = "1.1.0"

[workspace]
members = [
    "microwave",
    "tune-cli",
]