name: Run test suite

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    name: Run test suite on Linux

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install libxcb-composite0-dev libasound2-dev
    - name: Ensure code is properly formatted
      run: cargo fmt --all -- --check
    - name: Ensure all lints pass
      run: cargo clippy --workspace
    - name: Run tests
      run: cargo test --workspace
    - name: Build
      run: cargo build --workspace
