name: Run test suite

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    name: Run test suite on Linux

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: sudo apt update && sudo apt install libasound2-dev
      - name: Ensure code is properly formatted
        run: cargo fmt --all -- --check
      - name: Ensure all lints pass
        run: cargo clippy --workspace --features="tune-cli/build-tune-web"
      - name: Run tests
        run: cargo test --workspace --features="tune-cli/build-tune-web"
      - name: Build
        run: cargo build --workspace --features="tune-cli/build-tune-web"
