name: Run test suite

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    name: Run test suite on macOS

    runs-on: macos-latest # Use macos-latest for MIDI support in tests

    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Ensure code is properly formatted
        run: cargo fmt --all -- --check
      - name: Ensure all lints pass
        run: cargo clippy --workspace
      - name: Build
        run: cargo build --workspace
      - name: Run tests
        run: cargo test --workspace

  run-tests-wasm:
    name: Run checks on Linux (WASM)

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: '-D warnings --cfg getrandom_backend="wasm_js"'

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Ensure all lints pass
        run: cargo clippy --workspace --target wasm32-unknown-unknown
      - name: Build
        run: cargo build --workspace --target wasm32-unknown-unknown
